// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package loggertest

import (
	"context"
	"github.com/clarktrimble/jed/logger"
	"sync"
)

// Ensure, that LoggerMock does implement logger.Logger.
// If this is not the case, regenerate this file with moq.
var _ logger.Logger = &LoggerMock{}

// LoggerMock is a mock implementation of logger.Logger.
//
//	func TestSomethingThatUsesLogger(t *testing.T) {
//
//		// make and configure a mocked logger.Logger
//		mockedLogger := &LoggerMock{
//			DebugFunc: func(ctx context.Context, msg string, kv ...any)  {
//				panic("mock out the Debug method")
//			},
//			ErrorFunc: func(ctx context.Context, msg string, err error, kv ...any)  {
//				panic("mock out the Error method")
//			},
//			GetLevelFunc: func() string {
//				panic("mock out the GetLevel method")
//			},
//			InfoFunc: func(ctx context.Context, msg string, kv ...any)  {
//				panic("mock out the Info method")
//			},
//			SetLevelFunc: func(ctx context.Context, level string) error {
//				panic("mock out the SetLevel method")
//			},
//			TraceFunc: func(ctx context.Context, msg string, kv ...any)  {
//				panic("mock out the Trace method")
//			},
//			WithFieldsFunc: func(ctx context.Context, kv ...any) context.Context {
//				panic("mock out the WithFields method")
//			},
//		}
//
//		// use mockedLogger in code that requires logger.Logger
//		// and then make assertions.
//
//	}
type LoggerMock struct {
	// DebugFunc mocks the Debug method.
	DebugFunc func(ctx context.Context, msg string, kv ...any)

	// ErrorFunc mocks the Error method.
	ErrorFunc func(ctx context.Context, msg string, err error, kv ...any)

	// GetLevelFunc mocks the GetLevel method.
	GetLevelFunc func() string

	// InfoFunc mocks the Info method.
	InfoFunc func(ctx context.Context, msg string, kv ...any)

	// SetLevelFunc mocks the SetLevel method.
	SetLevelFunc func(ctx context.Context, level string) error

	// TraceFunc mocks the Trace method.
	TraceFunc func(ctx context.Context, msg string, kv ...any)

	// WithFieldsFunc mocks the WithFields method.
	WithFieldsFunc func(ctx context.Context, kv ...any) context.Context

	// calls tracks calls to the methods.
	calls struct {
		// Debug holds details about calls to the Debug method.
		Debug []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Kv is the kv argument value.
			Kv []any
		}
		// Error holds details about calls to the Error method.
		Error []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Err is the err argument value.
			Err error
			// Kv is the kv argument value.
			Kv []any
		}
		// GetLevel holds details about calls to the GetLevel method.
		GetLevel []struct {
		}
		// Info holds details about calls to the Info method.
		Info []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Kv is the kv argument value.
			Kv []any
		}
		// SetLevel holds details about calls to the SetLevel method.
		SetLevel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Level is the level argument value.
			Level string
		}
		// Trace holds details about calls to the Trace method.
		Trace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// Kv is the kv argument value.
			Kv []any
		}
		// WithFields holds details about calls to the WithFields method.
		WithFields []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Kv is the kv argument value.
			Kv []any
		}
	}
	lockDebug      sync.RWMutex
	lockError      sync.RWMutex
	lockGetLevel   sync.RWMutex
	lockInfo       sync.RWMutex
	lockSetLevel   sync.RWMutex
	lockTrace      sync.RWMutex
	lockWithFields sync.RWMutex
}

// Debug calls DebugFunc.
func (mock *LoggerMock) Debug(ctx context.Context, msg string, kv ...any) {
	if mock.DebugFunc == nil {
		panic("LoggerMock.DebugFunc: method is nil but Logger.Debug was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg string
		Kv  []any
	}{
		Ctx: ctx,
		Msg: msg,
		Kv:  kv,
	}
	mock.lockDebug.Lock()
	mock.calls.Debug = append(mock.calls.Debug, callInfo)
	mock.lockDebug.Unlock()
	mock.DebugFunc(ctx, msg, kv...)
}

// DebugCalls gets all the calls that were made to Debug.
// Check the length with:
//
//	len(mockedLogger.DebugCalls())
func (mock *LoggerMock) DebugCalls() []struct {
	Ctx context.Context
	Msg string
	Kv  []any
} {
	var calls []struct {
		Ctx context.Context
		Msg string
		Kv  []any
	}
	mock.lockDebug.RLock()
	calls = mock.calls.Debug
	mock.lockDebug.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *LoggerMock) Error(ctx context.Context, msg string, err error, kv ...any) {
	if mock.ErrorFunc == nil {
		panic("LoggerMock.ErrorFunc: method is nil but Logger.Error was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg string
		Err error
		Kv  []any
	}{
		Ctx: ctx,
		Msg: msg,
		Err: err,
		Kv:  kv,
	}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	mock.ErrorFunc(ctx, msg, err, kv...)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//
//	len(mockedLogger.ErrorCalls())
func (mock *LoggerMock) ErrorCalls() []struct {
	Ctx context.Context
	Msg string
	Err error
	Kv  []any
} {
	var calls []struct {
		Ctx context.Context
		Msg string
		Err error
		Kv  []any
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}

// GetLevel calls GetLevelFunc.
func (mock *LoggerMock) GetLevel() string {
	if mock.GetLevelFunc == nil {
		panic("LoggerMock.GetLevelFunc: method is nil but Logger.GetLevel was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetLevel.Lock()
	mock.calls.GetLevel = append(mock.calls.GetLevel, callInfo)
	mock.lockGetLevel.Unlock()
	return mock.GetLevelFunc()
}

// GetLevelCalls gets all the calls that were made to GetLevel.
// Check the length with:
//
//	len(mockedLogger.GetLevelCalls())
func (mock *LoggerMock) GetLevelCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetLevel.RLock()
	calls = mock.calls.GetLevel
	mock.lockGetLevel.RUnlock()
	return calls
}

// Info calls InfoFunc.
func (mock *LoggerMock) Info(ctx context.Context, msg string, kv ...any) {
	if mock.InfoFunc == nil {
		panic("LoggerMock.InfoFunc: method is nil but Logger.Info was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg string
		Kv  []any
	}{
		Ctx: ctx,
		Msg: msg,
		Kv:  kv,
	}
	mock.lockInfo.Lock()
	mock.calls.Info = append(mock.calls.Info, callInfo)
	mock.lockInfo.Unlock()
	mock.InfoFunc(ctx, msg, kv...)
}

// InfoCalls gets all the calls that were made to Info.
// Check the length with:
//
//	len(mockedLogger.InfoCalls())
func (mock *LoggerMock) InfoCalls() []struct {
	Ctx context.Context
	Msg string
	Kv  []any
} {
	var calls []struct {
		Ctx context.Context
		Msg string
		Kv  []any
	}
	mock.lockInfo.RLock()
	calls = mock.calls.Info
	mock.lockInfo.RUnlock()
	return calls
}

// SetLevel calls SetLevelFunc.
func (mock *LoggerMock) SetLevel(ctx context.Context, level string) error {
	if mock.SetLevelFunc == nil {
		panic("LoggerMock.SetLevelFunc: method is nil but Logger.SetLevel was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Level string
	}{
		Ctx:   ctx,
		Level: level,
	}
	mock.lockSetLevel.Lock()
	mock.calls.SetLevel = append(mock.calls.SetLevel, callInfo)
	mock.lockSetLevel.Unlock()
	return mock.SetLevelFunc(ctx, level)
}

// SetLevelCalls gets all the calls that were made to SetLevel.
// Check the length with:
//
//	len(mockedLogger.SetLevelCalls())
func (mock *LoggerMock) SetLevelCalls() []struct {
	Ctx   context.Context
	Level string
} {
	var calls []struct {
		Ctx   context.Context
		Level string
	}
	mock.lockSetLevel.RLock()
	calls = mock.calls.SetLevel
	mock.lockSetLevel.RUnlock()
	return calls
}

// Trace calls TraceFunc.
func (mock *LoggerMock) Trace(ctx context.Context, msg string, kv ...any) {
	if mock.TraceFunc == nil {
		panic("LoggerMock.TraceFunc: method is nil but Logger.Trace was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg string
		Kv  []any
	}{
		Ctx: ctx,
		Msg: msg,
		Kv:  kv,
	}
	mock.lockTrace.Lock()
	mock.calls.Trace = append(mock.calls.Trace, callInfo)
	mock.lockTrace.Unlock()
	mock.TraceFunc(ctx, msg, kv...)
}

// TraceCalls gets all the calls that were made to Trace.
// Check the length with:
//
//	len(mockedLogger.TraceCalls())
func (mock *LoggerMock) TraceCalls() []struct {
	Ctx context.Context
	Msg string
	Kv  []any
} {
	var calls []struct {
		Ctx context.Context
		Msg string
		Kv  []any
	}
	mock.lockTrace.RLock()
	calls = mock.calls.Trace
	mock.lockTrace.RUnlock()
	return calls
}

// WithFields calls WithFieldsFunc.
func (mock *LoggerMock) WithFields(ctx context.Context, kv ...any) context.Context {
	if mock.WithFieldsFunc == nil {
		panic("LoggerMock.WithFieldsFunc: method is nil but Logger.WithFields was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Kv  []any
	}{
		Ctx: ctx,
		Kv:  kv,
	}
	mock.lockWithFields.Lock()
	mock.calls.WithFields = append(mock.calls.WithFields, callInfo)
	mock.lockWithFields.Unlock()
	return mock.WithFieldsFunc(ctx, kv...)
}

// WithFieldsCalls gets all the calls that were made to WithFields.
// Check the length with:
//
//	len(mockedLogger.WithFieldsCalls())
func (mock *LoggerMock) WithFieldsCalls() []struct {
	Ctx context.Context
	Kv  []any
} {
	var calls []struct {
		Ctx context.Context
		Kv  []any
	}
	mock.lockWithFields.RLock()
	calls = mock.calls.WithFields
	mock.lockWithFields.RUnlock()
	return calls
}
